use_frameworks!

target 'XJGrowthRecord_Example' do
  pod 'XJGrowthRecord', :path => '../'

  target 'XJGrowthRecord_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    pod 'XJComponent'
  end
end
